import type { Movie } from "@/types/movie";

const tmdb = (p: string) => `https://image.tmdb.org/t/p/w780${p}`;

export const MOVIES: Movie[] = [
  {
    id: "interstellar",
    title: "Interstellar",
    year: "2014",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    director: "Christopher Nolan",
    runtime: "2h 49m",
    poster: tmdb("/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"),
    tags: ["Sci-Fi", "Space", "Emotional", "Mind-Bending"],
    streaming: ["Netflix", "Prime Video", "Apple TV"],
    youtube: [
      { title: "Interstellar Ending Explained", query: "interstellar ending explained" },
      { title: "Hidden Details You Missed", query: "interstellar hidden details" },
      { title: "Christopher Nolan Interview", query: "christopher nolan interstellar interview" },
      { title: "The Science Behind Interstellar", query: "science behind interstellar kip thorne" },
    ],
  },
  {
    id: "arrival",
    title: "Arrival",
    year: "2016",
    tagline: "Why are they here?",
    director: "Denis Villeneuve",
    runtime: "1h 56m",
    poster: tmdb("/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg"),
    tags: ["Sci-Fi", "Emotional", "Mind-Bending"],
    streaming: ["Prime Video", "Apple TV"],
    youtube: [
      { title: "Arrival Ending Explained", query: "arrival ending explained" },
      { title: "The Linguistics of Arrival", query: "arrival linguistics heptapod" },
      { title: "Villeneuve Interview", query: "denis villeneuve arrival interview" },
      { title: "Time Theory in Arrival", query: "arrival time theory" },
    ],
  },
  {
    id: "blade-runner-2049",
    title: "Blade Runner 2049",
    year: "2017",
    tagline: "The key to the future is finally unearthed.",
    director: "Denis Villeneuve",
    runtime: "2h 44m",
    poster: tmdb("/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg"),
    tags: ["Sci-Fi", "Mind-Bending"],
    streaming: ["Netflix", "Apple TV"],
    youtube: [
      { title: "BR2049 Ending Explained", query: "blade runner 2049 ending explained" },
      { title: "The Visual Language of BR2049", query: "blade runner 2049 cinematography" },
      { title: "Roger Deakins Lighting", query: "roger deakins blade runner 2049" },
      { title: "What Makes Us Human", query: "blade runner 2049 themes" },
    ],
  },
  {
    id: "dune",
    title: "Dune",
    year: "2021",
    tagline: "It begins.",
    director: "Denis Villeneuve",
    runtime: "2h 35m",
    poster: tmdb("/d5NXSklXo0qyIYkgV94XAgMIckC.jpg"),
    tags: ["Sci-Fi", "Space", "Emotional"],
    streaming: ["Netflix", "Prime Video"],
    youtube: [
      { title: "Dune Lore Explained", query: "dune lore explained" },
      { title: "Hans Zimmer's Score", query: "dune hans zimmer score" },
      { title: "Behind the Scenes", query: "dune behind the scenes villeneuve" },
      { title: "House Atreides Deep Dive", query: "house atreides explained" },
    ],
  },
  {
    id: "inception",
    title: "Inception",
    year: "2010",
    tagline: "Your mind is the scene of the crime.",
    director: "Christopher Nolan",
    runtime: "2h 28m",
    poster: tmdb("/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg"),
    tags: ["Mind-Bending", "Sci-Fi"],
    streaming: ["Netflix", "Apple TV"],
    youtube: [
      { title: "Inception Ending Explained", query: "inception ending explained" },
      { title: "Every Dream Level", query: "inception dream levels" },
      { title: "Nolan on Inception", query: "christopher nolan inception interview" },
      { title: "The Spinning Top Theory", query: "inception spinning top theory" },
    ],
  },
  {
    id: "2001",
    title: "2001: A Space Odyssey",
    year: "1968",
    tagline: "The ultimate trip.",
    director: "Stanley Kubrick",
    runtime: "2h 29m",
    poster: tmdb("/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg"),
    tags: ["Sci-Fi", "Space", "Mind-Bending"],
    streaming: ["Prime Video", "Apple TV"],
    youtube: [
      { title: "2001 Ending Decoded", query: "2001 space odyssey ending explained" },
      { title: "Kubrick's Vision", query: "kubrick 2001 vision" },
      { title: "The Monolith Theory", query: "2001 monolith theory" },
      { title: "HAL 9000 Explained", query: "hal 9000 explained" },
    ],
  },
  {
    id: "tenet",
    title: "Tenet",
    year: "2020",
    tagline: "Time runs out.",
    director: "Christopher Nolan",
    runtime: "2h 30m",
    poster: tmdb("/k68nPLbIST6NP96JmTxmZijEvCA.jpg"),
    tags: ["Mind-Bending", "Sci-Fi"],
    streaming: ["Netflix", "Apple TV"],
    youtube: [
      { title: "Tenet Timeline Explained", query: "tenet timeline explained" },
      { title: "Inversion Physics", query: "tenet inversion explained" },
      { title: "Nolan Breaks It Down", query: "nolan tenet interview" },
      { title: "Hidden Connections", query: "tenet hidden details" },
    ],
  },
  {
    id: "annihilation",
    title: "Annihilation",
    year: "2018",
    tagline: "It's not like us. It's not like anything.",
    director: "Alex Garland",
    runtime: "1h 55m",
    poster: tmdb("/d3qXxvZx88dyZGltCXkfqkXp4LE.jpg"),
    tags: ["Sci-Fi", "Mind-Bending", "Emotional"],
    streaming: ["Netflix", "Prime Video"],
    youtube: [
      { title: "The Shimmer Explained", query: "annihilation shimmer explained" },
      { title: "Ending Decoded", query: "annihilation ending explained" },
      { title: "Alex Garland Interview", query: "alex garland annihilation" },
      { title: "Symbolism Deep Dive", query: "annihilation symbolism" },
    ],
  },
  {
    id: "ad-astra",
    title: "Ad Astra",
    year: "2019",
    tagline: "The answers we seek are just outside our reach.",
    director: "James Gray",
    runtime: "2h 03m",
    poster: tmdb("/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg"),
    tags: ["Space", "Emotional", "Sci-Fi"],
    streaming: ["Disney+", "Apple TV"],
    youtube: [
      { title: "Ad Astra Ending Explained", query: "ad astra ending explained" },
      { title: "Father-Son Themes", query: "ad astra father son" },
      { title: "Brad Pitt Interview", query: "brad pitt ad astra interview" },
      { title: "Realistic Space Films", query: "realistic space films" },
    ],
  },
  {
    id: "gravity",
    title: "Gravity",
    year: "2013",
    tagline: "Don't let go.",
    director: "Alfonso Cuarón",
    runtime: "1h 31m",
    poster: tmdb("/kvVqJEDP2cIO5x3W7TKbXkU6jKn.jpg"),
    tags: ["Space", "Emotional"],
    streaming: ["Netflix", "Apple TV"],
    youtube: [
      { title: "How They Filmed Gravity", query: "how they filmed gravity" },
      { title: "The Long Take", query: "gravity long take" },
      { title: "Cuarón Interview", query: "alfonso cuaron gravity" },
      { title: "Real ISS vs Film", query: "gravity vs real iss" },
    ],
  },
  {
    id: "matrix",
    title: "The Matrix",
    year: "1999",
    tagline: "Welcome to the real world.",
    director: "The Wachowskis",
    runtime: "2h 16m",
    poster: tmdb("/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg"),
    tags: ["Sci-Fi", "Mind-Bending"],
    streaming: ["Netflix", "Prime Video"],
    youtube: [
      { title: "Red Pill vs Blue Pill", query: "matrix red pill blue pill" },
      { title: "Bullet Time Explained", query: "matrix bullet time" },
      { title: "Philosophy of the Matrix", query: "philosophy of the matrix" },
      { title: "Hidden Meanings", query: "matrix hidden meanings" },
    ],
  },
  {
    id: "solaris",
    title: "Solaris",
    year: "1972",
    tagline: "A meditation on memory and love.",
    director: "Andrei Tarkovsky",
    runtime: "2h 47m",
    poster: tmdb("/4QnGAm3MaQPMBZ2qFaXG5GqLgKn.jpg"),
    tags: ["Space", "Emotional", "Mind-Bending"],
    streaming: ["Apple TV"],
    youtube: [
      { title: "Tarkovsky's Solaris", query: "tarkovsky solaris analysis" },
      { title: "Memory & Identity", query: "solaris memory identity" },
      { title: "Slow Cinema Explained", query: "slow cinema tarkovsky" },
      { title: "Solaris vs the Remake", query: "solaris 1972 vs 2002" },
    ],
  },
  {
    id: "her",
    title: "Her",
    year: "2013",
    tagline: "A Spike Jonze love story.",
    director: "Spike Jonze",
    runtime: "2h 06m",
    poster: tmdb("/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg"),
    tags: ["Romance", "Emotional", "Sci-Fi"],
    streaming: ["Netflix", "Prime Video", "Apple TV"],
    youtube: [
      { title: "Her Ending Explained", query: "Her 2013 ending explained" },
      { title: "The Loneliness of Her", query: "Her movie loneliness analysis" },
      { title: "Spike Jonze Interview", query: "Spike Jonze Her interview" },
      { title: "Love in the Digital Age", query: "Her movie love digital age analysis" },
    ],
  },
  {
    id: "eternal-sunshine",
    title: "Eternal Sunshine of the Spotless Mind",
    year: "2004",
    tagline: "You can erase someone from your mind. Getting them out of your heart is another story.",
    director: "Michel Gondry",
    runtime: "1h 48m",
    poster: tmdb("/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg"),
    tags: ["Romance", "Emotional", "Mind-Bending"],
    streaming: ["Prime Video", "Apple TV"],
    youtube: [
      { title: "Eternal Sunshine Ending Explained", query: "Eternal Sunshine of the Spotless Mind ending explained" },
      { title: "Memory and Love Analysis", query: "Eternal Sunshine memory love analysis" },
      { title: "Charlie Kaufman Screenwriting", query: "Charlie Kaufman Eternal Sunshine screenplay" },
      { title: "Why It Still Hurts", query: "Eternal Sunshine of the Spotless Mind emotional analysis" },
    ],
  },
  {
    id: "la-la-land",
    title: "La La Land",
    year: "2016",
    tagline: "Here's to the fools who dream.",
    director: "Damien Chazelle",
    runtime: "2h 08m",
    poster: tmdb("/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg"),
    tags: ["Romance", "Emotional"],
    streaming: ["Netflix", "Prime Video", "Apple TV"],
    youtube: [
      { title: "La La Land Ending Explained", query: "La La Land ending explained" },
      { title: "The Epilogue Explained", query: "La La Land epilogue explained" },
      { title: "Damien Chazelle Interview", query: "Damien Chazelle La La Land interview" },
      { title: "City of Stars Analysis", query: "La La Land City of Stars analysis" },
    ],
  },
  {
    id: "before-sunrise",
    title: "Before Sunrise",
    year: "1995",
    tagline: "Can the greatest romance of your life last only one night?",
    director: "Richard Linklater",
    runtime: "1h 41m",
    poster: tmdb("/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg"),
    tags: ["Romance", "Emotional"],
    streaming: ["Prime Video", "Apple TV"],
    youtube: [
      { title: "Before Sunrise Analysis", query: "Before Sunrise analysis" },
      { title: "The Before Trilogy Explained", query: "Before trilogy explained" },
      { title: "Linklater on Romance", query: "Richard Linklater Before Sunrise interview" },
      { title: "Why Before Sunrise Works", query: "Why Before Sunrise is romantic" },
    ],
  },
  {
    id: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    year: "2015",
    tagline: "What a lovely day.",
    director: "George Miller",
    runtime: "2h 00m",
    poster: tmdb("/hA2ple9q4qnwxp3hKVNhroipsir.jpg"),
    tags: ["Action", "Thriller"],
    streaming: ["Netflix", "Prime Video", "Apple TV"],
    youtube: [
      { title: "Fury Road Practical Effects", query: "Mad Max Fury Road practical effects" },
      { title: "Visual Storytelling Analysis", query: "Mad Max Fury Road visual storytelling" },
      { title: "George Miller Interview", query: "George Miller Fury Road interview" },
      { title: "Why Fury Road Is Perfect Action", query: "Mad Max Fury Road action analysis" },
    ],
  },
  {
    id: "john-wick",
    title: "John Wick",
    year: "2014",
    tagline: "Don't set him off.",
    director: "Chad Stahelski",
    runtime: "1h 41m",
    poster: tmdb("/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg"),
    tags: ["Action", "Thriller", "Noir"],
    streaming: ["Prime Video", "Apple TV"],
    youtube: [
      { title: "John Wick Fight Choreography", query: "John Wick fight choreography" },
      { title: "The Continental Explained", query: "John Wick Continental explained" },
      { title: "Chad Stahelski Interview", query: "Chad Stahelski John Wick interview" },
      { title: "Gun-Fu Breakdown", query: "John Wick gun fu breakdown" },
    ],
  },
  {
    id: "se7en",
    title: "Se7en",
    year: "1995",
    tagline: "Seven deadly sins. Seven ways to die.",
    director: "David Fincher",
    runtime: "2h 07m",
    poster: tmdb("/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg"),
    tags: ["Thriller", "Noir"],
    streaming: ["Netflix", "Prime Video", "Apple TV"],
    youtube: [
      { title: "Se7en Ending Explained", query: "Se7en ending explained" },
      { title: "David Fincher's Darkness", query: "Se7en David Fincher analysis" },
      { title: "What's in the Box?", query: "Se7en what's in the box analysis" },
      { title: "Se7en Cinematography", query: "Se7en cinematography analysis" },
    ],
  },
  {
    id: "the-dark-knight",
    title: "The Dark Knight",
    year: "2008",
    tagline: "Why so serious?",
    director: "Christopher Nolan",
    runtime: "2h 32m",
    poster: tmdb("/qJ2tW6WMUDux911r6m7haRef0WH.jpg"),
    tags: ["Action", "Thriller", "Noir"],
    streaming: ["Netflix", "Prime Video", "Apple TV"],
    youtube: [
      { title: "The Dark Knight Ending Explained", query: "The Dark Knight ending explained" },
      { title: "Joker Philosophy", query: "The Dark Knight Joker philosophy" },
      { title: "Nolan's Crime Epic", query: "The Dark Knight crime epic analysis" },
      { title: "IMAX Behind the Scenes", query: "The Dark Knight IMAX behind the scenes" },
    ],
  },
  {
    id: "parasite", title: "Parasite", year: "2019", tagline: "Act like you own the place.",
    director: "Bong Joon-ho", runtime: "2h 12m",
    poster: tmdb("/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"),
    tags: ["Thriller", "Noir", "Emotional"], streaming: ["Netflix", "Prime Video"],
    youtube: [{ title: "Parasite Ending Explained", query: "parasite ending explained" }],
  },
  {
    id: "oppenheimer", title: "Oppenheimer", year: "2023", tagline: "The world forever changes.",
    director: "Christopher Nolan", runtime: "3h 00m",
    poster: tmdb("/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"),
    tags: ["Thriller", "Emotional"], streaming: ["Apple TV", "Prime Video"],
    youtube: [{ title: "Oppenheimer Explained", query: "oppenheimer explained" }],
  },
  {
    id: "the-batman", title: "The Batman", year: "2022", tagline: "Unmask the truth.",
    director: "Matt Reeves", runtime: "2h 56m",
    poster: tmdb("/74xTEgt7R36Fpooo50r9T25onhq.jpg"),
    tags: ["Action", "Noir", "Thriller"], streaming: ["Netflix", "Apple TV"],
    youtube: [{ title: "The Batman Riddler", query: "the batman riddler explained" }],
  },
  {
    id: "joker", title: "Joker", year: "2019", tagline: "Put on a happy face.",
    director: "Todd Phillips", runtime: "2h 02m",
    poster: tmdb("/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg"),
    tags: ["Noir", "Thriller", "Emotional"], streaming: ["Netflix", "Prime Video"],
    youtube: [{ title: "Joker Analysis", query: "joker 2019 analysis" }],
  },
  {
    id: "dune-two", title: "Dune: Part Two", year: "2024", tagline: "Long live the fighters.",
    director: "Denis Villeneuve", runtime: "2h 46m",
    poster: tmdb("/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg"),
    tags: ["Sci-Fi", "Space", "Action"], streaming: ["Apple TV", "Prime Video"],
    youtube: [{ title: "Dune Part Two Lore", query: "dune part two lore" }],
  },
  {
    id: "spider-verse", title: "Spider-Man: Into the Spider-Verse", year: "2018",
    tagline: "More than one wears the mask.", director: "Persichetti/Ramsey/Rothman", runtime: "1h 57m",
    poster: tmdb("/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg"),
    tags: ["Action", "Sci-Fi", "Emotional"], streaming: ["Netflix"],
    youtube: [{ title: "Spider-Verse Animation", query: "spider verse animation breakdown" }],
  },
  {
    id: "across-spider-verse", title: "Across the Spider-Verse", year: "2023",
    tagline: "It's how the story is supposed to go.", director: "Dos Santos/Powers/Thompson", runtime: "2h 20m",
    poster: tmdb("/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg"),
    tags: ["Action", "Sci-Fi", "Emotional", "Mind-Bending"], streaming: ["Netflix"],
    youtube: [{ title: "Across the Spider-Verse Ending", query: "across the spider verse ending" }],
  },
  {
    id: "everything-everywhere", title: "Everything Everywhere All at Once", year: "2022",
    tagline: "The universe is so much bigger than you realize.", director: "Daniels", runtime: "2h 19m",
    poster: tmdb("/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg"),
    tags: ["Mind-Bending", "Sci-Fi", "Emotional"], streaming: ["Prime Video"],
    youtube: [{ title: "EEAAO Analysis", query: "everything everywhere all at once analysis" }],
  },
  {
    id: "whiplash", title: "Whiplash", year: "2014", tagline: "The road to greatness can take you to the edge.",
    director: "Damien Chazelle", runtime: "1h 47m",
    poster: tmdb("/7fn624j5lj3xTme2SgiLCeuedmO.jpg"),
    tags: ["Emotional", "Thriller"], streaming: ["Netflix", "Apple TV"],
    youtube: [{ title: "Whiplash Ending", query: "whiplash ending explained" }],
  },
  {
    id: "the-prestige", title: "The Prestige", year: "2006", tagline: "Are you watching closely?",
    director: "Christopher Nolan", runtime: "2h 10m",
    poster: tmdb("/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg"),
    tags: ["Mind-Bending", "Thriller", "Noir"], streaming: ["Prime Video", "Apple TV"],
    youtube: [{ title: "Prestige Ending", query: "the prestige ending explained" }],
  },
  {
    id: "memento", title: "Memento", year: "2000", tagline: "Some memories are best forgotten.",
    director: "Christopher Nolan", runtime: "1h 53m",
    poster: tmdb("/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg"),
    tags: ["Mind-Bending", "Noir", "Thriller"], streaming: ["Prime Video"],
    youtube: [{ title: "Memento Explained", query: "memento explained" }],
  },
  {
    id: "fight-club", title: "Fight Club", year: "1999", tagline: "Mischief. Mayhem. Soap.",
    director: "David Fincher", runtime: "2h 19m",
    poster: tmdb("/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg"),
    tags: ["Mind-Bending", "Thriller", "Noir"], streaming: ["Netflix"],
    youtube: [{ title: "Fight Club Analysis", query: "fight club analysis" }],
  },
  {
    id: "pulp-fiction", title: "Pulp Fiction", year: "1994", tagline: "You won't know the facts until you've seen the fiction.",
    director: "Quentin Tarantino", runtime: "2h 34m",
    poster: tmdb("/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg"),
    tags: ["Noir", "Thriller"], streaming: ["Netflix", "Apple TV"],
    youtube: [{ title: "Pulp Fiction Timeline", query: "pulp fiction timeline" }],
  },
  {
    id: "godfather", title: "The Godfather", year: "1972", tagline: "An offer you can't refuse.",
    director: "Francis Ford Coppola", runtime: "2h 55m",
    poster: tmdb("/3bhkrj58Vtu7enYsRolD1fZdja1.jpg"),
    tags: ["Noir", "Emotional"], streaming: ["Paramount", "Apple TV"] as any,
    youtube: [{ title: "Godfather Legacy", query: "the godfather legacy" }],
  },
  {
    id: "goodfellas", title: "Goodfellas", year: "1990", tagline: "Three decades of life in the Mafia.",
    director: "Martin Scorsese", runtime: "2h 26m",
    poster: tmdb("/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg"),
    tags: ["Noir", "Thriller"], streaming: ["Netflix"],
    youtube: [{ title: "Goodfellas Tracking Shot", query: "goodfellas tracking shot" }],
  },
  {
    id: "shawshank", title: "The Shawshank Redemption", year: "1994", tagline: "Fear can hold you prisoner. Hope can set you free.",
    director: "Frank Darabont", runtime: "2h 22m",
    poster: tmdb("/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg"),
    tags: ["Emotional"], streaming: ["Netflix", "Prime Video"],
    youtube: [{ title: "Shawshank Analysis", query: "shawshank redemption analysis" }],
  },
  {
    id: "schindlers-list", title: "Schindler's List", year: "1993", tagline: "Whoever saves one life, saves the world entire.",
    director: "Steven Spielberg", runtime: "3h 15m",
    poster: tmdb("/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg"),
    tags: ["Emotional"], streaming: ["Netflix"],
    youtube: [{ title: "Schindler's List Legacy", query: "schindlers list legacy" }],
  },
  {
    id: "no-country", title: "No Country for Old Men", year: "2007", tagline: "There are no clean getaways.",
    director: "Coen Brothers", runtime: "2h 02m",
    poster: tmdb("/6d5XOczc226jECq0LIX0siKtgHR.jpg"),
    tags: ["Noir", "Thriller"], streaming: ["Apple TV"],
    youtube: [{ title: "No Country Ending", query: "no country for old men ending" }],
  },
  {
    id: "there-will-be-blood", title: "There Will Be Blood", year: "2007", tagline: "When ambition meets faith.",
    director: "Paul Thomas Anderson", runtime: "2h 38m",
    poster: tmdb("/fa0RDkAlCec0STeMNAhPaF89q4r.jpg"),
    tags: ["Noir", "Emotional"], streaming: ["Apple TV"],
    youtube: [{ title: "TWBB Analysis", query: "there will be blood analysis" }],
  },
  {
    id: "social-network", title: "The Social Network", year: "2010", tagline: "You don't get to 500 million friends without making a few enemies.",
    director: "David Fincher", runtime: "2h 00m",
    poster: tmdb("/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg"),
    tags: ["Noir", "Emotional"], streaming: ["Netflix"],
    youtube: [{ title: "Social Network Score", query: "social network score trent reznor" }],
  },
  {
    id: "drive", title: "Drive", year: "2011", tagline: "There are no clean getaways.",
    director: "Nicolas Winding Refn", runtime: "1h 40m",
    poster: tmdb("/602vevIURmpDfzbnu96ZIZdbjBI.jpg"),
    tags: ["Noir", "Action", "Thriller"], streaming: ["Netflix", "Prime Video"],
    youtube: [{ title: "Drive Aesthetic", query: "drive 2011 aesthetic" }],
  },
  {
    id: "wolf-of-wall-street", title: "The Wolf of Wall Street", year: "2013", tagline: "More is never enough.",
    director: "Martin Scorsese", runtime: "3h 00m",
    poster: tmdb("/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg"),
    tags: ["Noir"], streaming: ["Netflix", "Prime Video"],
    youtube: [{ title: "Wolf of Wall Street Ending", query: "wolf of wall street ending" }],
  },
  {
    id: "django", title: "Django Unchained", year: "2012", tagline: "Life, liberty and the pursuit of vengeance.",
    director: "Quentin Tarantino", runtime: "2h 45m",
    poster: tmdb("/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg"),
    tags: ["Action", "Noir"], streaming: ["Netflix"],
    youtube: [{ title: "Django Score", query: "django unchained score" }],
  },
  {
    id: "inglourious", title: "Inglourious Basterds", year: "2009", tagline: "A basterd's work is never done.",
    director: "Quentin Tarantino", runtime: "2h 33m",
    poster: tmdb("/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg"),
    tags: ["Action", "Thriller"], streaming: ["Netflix"],
    youtube: [{ title: "Opening Scene Tension", query: "inglourious basterds opening" }],
  },
  {
    id: "departed", title: "The Departed", year: "2006", tagline: "Lies. Betrayal. Sacrifice.",
    director: "Martin Scorsese", runtime: "2h 31m",
    poster: tmdb("/nT97ifVT2J1yMQmeq20Qblg61T.jpg"),
    tags: ["Noir", "Thriller"], streaming: ["Netflix", "Apple TV"],
    youtube: [{ title: "Departed Ending", query: "the departed ending explained" }],
  },
  {
    id: "heat", title: "Heat", year: "1995", tagline: "A Los Angeles crime saga.",
    director: "Michael Mann", runtime: "2h 50m",
    poster: tmdb("/umSVjVdbVwtx5ryCA2QXL44Durm.jpg"),
    tags: ["Noir", "Thriller", "Action"], streaming: ["Apple TV"],
    youtube: [{ title: "Heat Diner Scene", query: "heat diner scene analysis" }],
  },
  {
    id: "lotr-fellowship", title: "The Fellowship of the Ring", year: "2001",
    tagline: "One ring to rule them all.", director: "Peter Jackson", runtime: "2h 58m",
    poster: tmdb("/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg"),
    tags: ["Emotional"], streaming: ["Prime Video"],
    youtube: [{ title: "Fellowship Behind the Scenes", query: "fellowship of the ring behind the scenes" }],
  },
  {
    id: "lotr-two-towers", title: "The Two Towers", year: "2002", tagline: "A new power is rising.",
    director: "Peter Jackson", runtime: "2h 59m",
    poster: tmdb("/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg"),
    tags: ["Action", "Emotional"], streaming: ["Prime Video"],
    youtube: [{ title: "Helm's Deep Breakdown", query: "helms deep breakdown" }],
  },
  {
    id: "lotr-return", title: "The Return of the King", year: "2003", tagline: "The eye of the enemy is moving.",
    director: "Peter Jackson", runtime: "3h 21m",
    poster: tmdb("/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg"),
    tags: ["Emotional", "Action"], streaming: ["Prime Video"],
    youtube: [
      { title: "Return of the King Endings", query: "return of the king endings" },
    ],
  },
  {
    id: "star-wars-empire", title: "The Empire Strikes Back", year: "1980", tagline: "The Adventure Continues.",
    director: "Irvin Kershner", runtime: "2h 04m",
    poster: tmdb("/7BuH8itoSrLExs2YZSsM01Qk2no.jpg"),
    tags: ["Space", "Sci-Fi"], streaming: ["Disney+"],
    youtube: [{ title: "Empire Strikes Back Legacy", query: "empire strikes back legacy" }],
  },
  {
    id: "alien", title: "Alien", year: "1979", tagline: "In space no one can hear you scream.",
    director: "Ridley Scott", runtime: "1h 57m",
    poster: tmdb("/vfrQk5IPloGg1v9Rzbb2gJDuVmd.jpg"),
    tags: ["Space", "Sci-Fi", "Thriller"], streaming: ["Disney+"],
    youtube: [{ title: "Alien Chestburster", query: "alien chestburster scene" }],
  },
  {
    id: "aliens", title: "Aliens", year: "1986", tagline: "This time it's war.",
    director: "James Cameron", runtime: "2h 17m",
    poster: tmdb("/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg"),
    tags: ["Space", "Sci-Fi", "Action"], streaming: ["Disney+"],
    youtube: [{ title: "Aliens vs Alien", query: "aliens vs alien comparison" }],
  },
  {
    id: "spirited-away", title: "Spirited Away", year: "2001", tagline: "The tunnel led Chihiro to a mysterious town.",
    director: "Hayao Miyazaki", runtime: "2h 05m",
    poster: tmdb("/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg"),
    tags: ["Emotional", "Mind-Bending"], streaming: ["Netflix"],
    youtube: [{ title: "Spirited Away Meaning", query: "spirited away meaning" }],
  },
  {
    id: "your-name", title: "Your Name", year: "2016", tagline: "Two souls. One destiny.",
    director: "Makoto Shinkai", runtime: "1h 46m",
    poster: tmdb("/q719jXXEzOoYaps6babgKnONONX.jpg"),
    tags: ["Romance", "Emotional", "Mind-Bending"], streaming: ["Prime Video"],
    youtube: [{ title: "Your Name Ending", query: "your name ending explained" }],
  },
  {
    id: "akira", title: "Akira", year: "1988", tagline: "Neo-Tokyo is about to explode.",
    director: "Katsuhiro Otomo", runtime: "2h 04m",
    poster: tmdb("/neZ0ykimSepWRPF5AhwM73lukMa.jpg"),
    tags: ["Sci-Fi", "Mind-Bending"], streaming: ["Prime Video"],
    youtube: [{ title: "Akira Influence", query: "akira anime influence" }],
  },
  {
    id: "ghost-in-the-shell", title: "Ghost in the Shell", year: "1995", tagline: "It found a voice. Now it needs a body.",
    director: "Mamoru Oshii", runtime: "1h 23m",
    poster: tmdb("/9gC88zYUBARRSThcG93MvW14sqx.jpg"),
    tags: ["Sci-Fi", "Mind-Bending"], streaming: ["Apple TV"],
    youtube: [{ title: "Ghost in the Shell Themes", query: "ghost in the shell themes" }],
  },
  {
    id: "blade-runner-1982", title: "Blade Runner", year: "1982", tagline: "Man has made his match. Now it's his problem.",
    director: "Ridley Scott", runtime: "1h 57m",
    poster: tmdb("/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg"),
    tags: ["Sci-Fi", "Noir", "Mind-Bending"], streaming: ["Apple TV"],
    youtube: [{ title: "Blade Runner Final Cut", query: "blade runner final cut" }],
  },
  {
    id: "ex-machina", title: "Ex Machina", year: "2014", tagline: "There is nothing more human than the will to survive.",
    director: "Alex Garland", runtime: "1h 48m",
    poster: tmdb("/btbRB7BrD887j5NrvjxceRDmaot.jpg"),
    tags: ["Sci-Fi", "Mind-Bending", "Thriller"], streaming: ["Netflix"],
    youtube: [{ title: "Ex Machina Ending", query: "ex machina ending explained" }],
  },
  {
    id: "arrival-ish-children-of-men", title: "Children of Men", year: "2006", tagline: "No children. No future. No hope.",
    director: "Alfonso Cuarón", runtime: "1h 49m",
    poster: tmdb("/k9IFG8yZ0c7vrEulFA4cVo5DSXR.jpg"),
    tags: ["Sci-Fi", "Emotional", "Thriller"], streaming: ["Apple TV"],
    youtube: [{ title: "Children of Men Long Take", query: "children of men long take" }],
  },
  {
    id: "the-thing", title: "The Thing", year: "1982", tagline: "Man is the warmest place to hide.",
    director: "John Carpenter", runtime: "1h 49m",
    poster: tmdb("/tzGY49kseSE9QAKk47uuDGwnSCu.jpg"),
    tags: ["Sci-Fi", "Thriller"], streaming: ["Apple TV"],
    youtube: [{ title: "The Thing Ending", query: "the thing ending explained" }],
  },
  {
    id: "shutter-island", title: "Shutter Island", year: "2010", tagline: "Someone is missing.",
    director: "Martin Scorsese", runtime: "2h 18m",
    poster: tmdb("/52nC7sw4uTayrPLqIVjvUFFNNZN.jpg"),
    tags: ["Thriller", "Mind-Bending"], streaming: ["Netflix"],
    youtube: [{ title: "Shutter Island Ending", query: "shutter island ending" }],
  },
  {
    id: "gone-girl", title: "Gone Girl", year: "2014", tagline: "You don't know what you've got till it's…gone.",
    director: "David Fincher", runtime: "2h 29m",
    poster: tmdb("/qd2DqmkBKozMaPS3sRrgXM6CTLh.jpg"),
    tags: ["Thriller", "Noir"], streaming: ["Apple TV"],
    youtube: [{ title: "Gone Girl Analysis", query: "gone girl analysis" }],
  },
  {
    id: "zodiac", title: "Zodiac", year: "2007", tagline: "There's more than one way to lose your life to a killer.",
    director: "David Fincher", runtime: "2h 37m",
    poster: tmdb("/6YOroFNVeMlSyQviJgPNJxZyAVK.jpg"),
    tags: ["Thriller", "Noir"], streaming: ["Netflix"],
    youtube: [{ title: "Zodiac Killer Theory", query: "zodiac killer film analysis" }],
  },
  {
    id: "get-out", title: "Get Out", year: "2017", tagline: "Just because you're invited, doesn't mean you're welcome.",
    director: "Jordan Peele", runtime: "1h 44m",
    poster: tmdb("/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg"),
    tags: ["Thriller", "Mind-Bending"], streaming: ["Netflix"],
    youtube: [{ title: "Get Out Symbolism", query: "get out symbolism" }],
  },
  {
    id: "hereditary", title: "Hereditary", year: "2018", tagline: "Every family tree hides a secret.",
    director: "Ari Aster", runtime: "2h 07m",
    poster: tmdb("/p81d4hVqfDqXkVT8nBzFXOpUm59.jpg"),
    tags: ["Thriller", "Mind-Bending"], streaming: ["Prime Video"],
    youtube: [{ title: "Hereditary Ending", query: "hereditary ending" }],
  },
  {
    id: "midsommar", title: "Midsommar", year: "2019", tagline: "Let the festivities begin.",
    director: "Ari Aster", runtime: "2h 28m",
    poster: tmdb("/iRFgZcwiEdc8sg5o3Y2VbW2zHTr.jpg"),
    tags: ["Thriller", "Mind-Bending"], streaming: ["Prime Video"],
    youtube: [{ title: "Midsommar Symbolism", query: "midsommar symbolism" }],
  },
  {
    id: "lighthouse", title: "The Lighthouse", year: "2019", tagline: "There is enchantment in the light.",
    director: "Robert Eggers", runtime: "1h 49m",
    poster: tmdb("/4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg"),
    tags: ["Mind-Bending", "Noir"], streaming: ["Apple TV"],
    youtube: [{ title: "Lighthouse Analysis", query: "the lighthouse analysis" }],
  },
  {
    id: "amelie", title: "Amélie", year: "2001", tagline: "She'll change your life.",
    director: "Jean-Pierre Jeunet", runtime: "2h 03m",
    poster: "https://upload.wikimedia.org/wikipedia/en/5/53/Amelie_poster.jpg",
    tags: ["Romance", "Emotional"], streaming: ["Apple TV"],
    youtube: [{ title: "Amelie Color Palette", query: "amelie color palette" }],
  },
  {
    id: "in-the-mood", title: "In the Mood for Love", year: "2000", tagline: "Feelings can creep up just like that.",
    director: "Wong Kar-wai", runtime: "1h 38m",
    poster: tmdb("/yI6dddIycSmG6cblDxfrkEQv7BN.jpg"),
    tags: ["Romance", "Emotional"], streaming: ["Apple TV"],
    youtube: [{ title: "Wong Kar-wai Style", query: "wong kar wai style" }],
  },
  {
    id: "moonlight", title: "Moonlight", year: "2016", tagline: "This is the story of a lifetime.",
    director: "Barry Jenkins", runtime: "1h 51m",
    poster: tmdb("/fFYBLu2Hnx27CWLOMd425ExDkgK.jpg"),
    tags: ["Emotional", "Romance"], streaming: ["Netflix"],
    youtube: [{ title: "Moonlight Cinematography", query: "moonlight cinematography" }],
  },
  {
    id: "call-me-by-your-name", title: "Call Me by Your Name", year: "2017", tagline: "Is it better to speak or to die?",
    director: "Luca Guadagnino", runtime: "2h 12m",
    poster: "https://upload.wikimedia.org/wikipedia/en/c/c9/CallMeByYourName2017.png",
    tags: ["Romance", "Emotional"], streaming: ["Netflix"],
    youtube: [{ title: "CMBYN Analysis", query: "call me by your name analysis" }],
  },
  {
    id: "before-sunset", title: "Before Sunset", year: "2004", tagline: "What if you had a second chance with the one that got away?",
    director: "Richard Linklater", runtime: "1h 20m",
    poster: tmdb("/gycdE1ARByGQcK4fYR2mgpU6OO.jpg"),
    tags: ["Romance", "Emotional"], streaming: ["Apple TV"],
    youtube: [{ title: "Before Sunset Walk and Talk", query: "before sunset analysis" }],
  },
  {
    id: "1917", title: "1917", year: "2019", tagline: "Time is the enemy.",
    director: "Sam Mendes", runtime: "1h 59m",
    poster: tmdb("/iZf0KyrE25z1sage4SYFLCCrMi9.jpg"),
    tags: ["Action", "Thriller", "Emotional"], streaming: ["Netflix"],
    youtube: [{ title: "1917 One Shot", query: "1917 one take cinematography" }],
  },
  {
    id: "saving-private-ryan", title: "Saving Private Ryan", year: "1998", tagline: "The mission is a man.",
    director: "Steven Spielberg", runtime: "2h 49m",
    poster: tmdb("/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg"),
    tags: ["Action", "Emotional"], streaming: ["Netflix"],
    youtube: [{ title: "Omaha Beach Scene", query: "saving private ryan omaha beach" }],
  },
  {
    id: "apocalypse-now", title: "Apocalypse Now", year: "1979", tagline: "The horror. The horror.",
    director: "Francis Ford Coppola", runtime: "2h 27m",
    poster: tmdb("/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg"),
    tags: ["Emotional", "Action", "Mind-Bending"], streaming: ["Apple TV"],
    youtube: [{ title: "Apocalypse Now Making Of", query: "hearts of darkness apocalypse now" }],
  },
  {
    id: "mulholland-drive", title: "Mulholland Drive", year: "2001", tagline: "A love story in the city of dreams.",
    director: "David Lynch", runtime: "2h 27m",
    poster: tmdb("/9Rj8l6gElLpRL7Kj17iZhrT5Zuw.jpg"),
    tags: ["Mind-Bending", "Noir", "Romance"], streaming: ["Apple TV"],
    youtube: [{ title: "Mulholland Drive Explained", query: "mulholland drive explained" }],
  },
  {
    id: "donnie-darko", title: "Donnie Darko", year: "2001", tagline: "Dark. Darker. Donnie Darko.",
    director: "Richard Kelly", runtime: "1h 53m",
    poster: tmdb("/fhQoQfejY1hUcwyuLgpBrYs6uFt.jpg"),
    tags: ["Mind-Bending", "Sci-Fi"], streaming: ["Prime Video"],
    youtube: [{ title: "Donnie Darko Theory", query: "donnie darko explained" }],
  },
  {
    id: "primer", title: "Primer", year: "2004", tagline: "What happens if it actually works?",
    director: "Shane Carruth", runtime: "1h 17m",
    poster: tmdb("/9rmIyAWXrwsRX5wbT2rsTuYsMVf.jpg"),
    tags: ["Mind-Bending", "Sci-Fi"], streaming: ["Apple TV"],
    youtube: [{ title: "Primer Timeline", query: "primer timeline explained" }],
  },
  {
    id: "coherence", title: "Coherence", year: "2013", tagline: "Nothing is more frightening than what's outside.",
    director: "James Ward Byrkit", runtime: "1h 29m",
    poster: tmdb("/52YBzdGZ4LIxqV4LTzU8mNwQKqV.jpg"),
    tags: ["Mind-Bending", "Sci-Fi", "Thriller"], streaming: ["Prime Video"],
    youtube: [{ title: "Coherence Explained", query: "coherence movie explained" }],
  },
];

export const ALL_TAGS = ["Sci-Fi", "Mind-Bending", "Space", "Emotional", "Thriller", "Noir", "Romance", "Action"];
